### ISSUE TITLE
Think you installed the wrong package

### ISSUE THREAD

**Issue by jimmywarting** [marismarcosta/learn-protractor#1]
actually believe you meant to install standard and not standardjs
https://github.com/marismarcosta/learn-protractor/blob/9b3ea5515eda328fc8de14eb8375d0854337da23/package.json#L40

**Comment by marismar** [comment]
> actually believe you meant to install standard and not standardjs
> https://github.com/marismarcosta/learn-protractor/blob/9b3ea5515eda328fc8de14eb8375d0854337da23/package.json#L40
Yes, I should have used standard, but standardjs worked fine.

**Comment by jimmywarting** [comment]
I don't think it dose, have you looked at their github repo? it dose literally nothing. it dose not seem like the real deal

**Comment by marismar** [comment]
> I don't think it dose, have you looked at their github repo? it dose literally nothing. it dose not seem like the real deal

You're right. I was using a local installation of standard, that's why I thought that standardjs was working. 
So, I have already changed standardjs to standard. 
Thank you very much!
